### ISSUE TITLE
"save with selected calibration" requires you to refresh the page instead of just showing the spectrum with the selected calibration

### ISSUE THREAD

**Issue by ethanbass** [publiclab/spectral-workbench#323] opened 2016-02-11 22:43 UTC
It's not such a big deal once you figure it out, but you have to refresh the page after saving a new spectrum in order for it to appear with the calibration... I tested this bug in firefox and in chrome on OS X maverick.

Also, a bigger problem i've just found, which is probably related: I have two calibrated spectra from the same session (i.e. I went back to the same window of spectral work bench after saving one spectrum and saved the next spectrum). The spectra are both calibrated, but when I go to compare them, the one I am trying to overlay is not calibrated. It doesn't matter what the order of operations is (I can pull up either spectrum and try to compare it to the other and the same problem arises).

I am attaching a screenshot of two spectra superimposed, where one is not showing up as calibrated. Perhaps it has something to do with the new operations function. I can only guess that the comparison function may not be accessing the "snapshot" where the calibration information has been saved.

<img width="1021" alt="screen shot 2016-02-11 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/15876283/12993404/91de9666-d0df-11e5-9b8e-8ba353826ab7.png">

**Comment by jywarren** [comment] 2016-02-11 22:55
Hmm, really? Are you sure it doesn't just take a little while? Is there any
way you can screenrecord this so I can try to reproduce it? Thanks!

**Comment by ethanbass** [comment] 2016-02-11 22:59
do you mean a video? or a screenshot?

**Comment by jywarren** [comment] 2016-02-11 23:06
Well if a video is a pain, a sequence of screenshots I guess? I'm just
trying to get as much information as possible.

**Comment by ethanbass** [comment] 2016-02-11 23:10
![screen shot 2016-02-11 at 5 05 40 pm](https://cloud.githubusercontent.com/assets/15876283/12993753/c6dcf2ca-d0e1-11e5-9f92-893d5ffe008a.jpg)


Here is a screenshot of what i'm talking about, this is after about 5 minutes and the browser doesn't appear to be loading anything. I don't know what time zone the app is working in. It says 23:01, but I think I uploaded the spectra at 5 pm my time and the picture as you can see if from 5:05. You'll notice that it says under notifications "this spectrum needs to be calibrated" but you can also see that the calibration operation has been completed.

When I refresh the page and take another screenshot, the calibration snaps into place and the notification goes away, as you can see below.

![screen shot 2016-02-11 at 5 09 00 pm](https://cloud.githubusercontent.com/assets/15876283/12993813/4ae96508-d0e2-11e5-9041-e207594811b6.jpg)

**Comment by jywarren** [comment] 2016-02-11 23:15
Ok thanks!!! Can you open a new issue for the timestamp though?

Thanks.

**Comment by jywarren** [comment] 2016-02-12 15:59
Can you open a new issue for the calibrated comparisons too? Thanks, Ethan!

**Comment by ethanbass** [comment] 2016-02-12 16:07
yeah

**Comment by jywarren** [comment] 2016-02-12 18:51
Awesome, very grateful. As to the above screenshots, it looks like the calibration is being generated, but it's not refreshing the graph once it's done. Thanks for giving it some time to see if it goes through. 

Reproduced; the log shows: https://gist.github.com/jywarren/3995e6416a6a69fdb34f

following up...

**Comment by jywarren** [comment] 2016-02-18 21:03
Checking if this has been resolved in v2.1.9...

**Comment by jywarren** [comment] 2016-02-18 21:04
I believe it is -- @ethanbass, can you try it out? Thanks!

**Closed by jywarren** 2016-02-18 21:04 UTC
Labels: bug, in progress
